#include "tabs/test.hpp"

enum class LemlibTunerPages {
    IDLE,
    DRIVEBASE_OBJECT_CONFIG,
    TRACKING_WHEEL_OBJECT_CONFIGS,
    LATERAL_CONTROLLER_OBJECT_CONFIG_KGAIN,
    LATERAL_CONTROLLER_OBJECT_CONFIG_ANTIWINDUP,
    LATERAL_CONTROLLER_OBJECT_CONFIG_SMALL_ERROR_RANGE,
    LATERAL_CONTROLLER_OBJECT_CONFIG_LARGE_ERROR_RANGE,
    LATERAL_CONTROLLER_OBJECT_CONFIG_SLEW,
    ANGULAR_CONTROLLER_OBJECT_CONFIG_KGAIN,
    ANGULAR_CONTROLLER_OBJECT_CONFIG_ANTIWINDUP,
    ANGULAR_CONTROLLER_OBJECT_CONFIG_SMALL_ERROR_RANGE,
    ANGULAR_CONTROLLER_OBJECT_CONFIG_LARGE_ERROR_RANGE,
    ANGULAR_CONTROLLER_OBJECT_CONFIG_SLEW,
    REVIEW_PG1,
    REVIEW_PG2,
    REVIEW_PG3
};

static LemlibTunerPages current_tuning_phase = LemlibTunerPages::IDLE;